baseURL = "https://wherwellcc.co.uk/"
languageCode = "en-gb"
theme = "alpha-church"
title = "Wherwell"

rssLimit = 5
paginate = 10

enableEmoji = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

enableInlineShortcodes = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
  category = "categories"
  report = "reports"

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Sponsors"
    url = "/sponsors"
    weight = 2

  [[menu.main]]
    name = "Play Cricket"
    url = "https://wherwell.play-cricket.com"
    weight = 3

  [[menu.main]]
    name = "Reports"
    url = "/categories/xi-reports/"
    weight = 4

  [[menu.main]]
    name = "Wherwell XI"
    parent = "Reports"
    url = "/categories/xi-reports/"
    weight = 5

  [[menu.main]]
    name = "Friendlies"
    parent = "Reports"
    url = "/categories/friendlyreports/"
    weight = 6

  [[menu.main]]
    name = "Averages"
    parent = "Reports"
    url = "/averages"
    weight = 7

  [[menu.main]]
    name = "Shop"
    url = "https://seriouscricket.co.uk/teamwear/stores/wherwell-cricket-club"
    weight = 8

  [[menu.main]]
    name = "Club Documents"
    url = "/documents"
    weight = 9

  [[menu.main]]
    name = "Find us"
    url = "/findus"
    weight = 10

  [[menu.main]]
    name = "Contact"
    url = "#cta"
    weight = 11

# Paramaters for the whole site
[params]
  title = "Wherwell Cricket Club"
  languageCode = "en" # For accessibility this needs to be set. You can find all language codes at https://www.w3schools.com/tags/ref_language_codes.asp
  instant_page = true

  customCSS = ["style/custom.css"]

  [params.favicon]
    sml = "/favicon-16x16.png"
    med = "/favicon-32x32.png"
    #lge = "example96.png"

  [params.banner]
    image = "img/banner.jpeg"

#  [params.style]
#    googleFonts = ["Cardo", "Crimson+Text", "Merriweather", "Playfair+Display:400,700", "Roboto+Slab"]

  [params.podcast]
    title = "Listen to Alpha Church"
    summary = "Alpha-Church sermons, talks, messages—podcasted."
    email = "test@example.com"
    copyright = "The files in the podcast are in the public domain."
    image = "img/podcast-cover.jpg"
    category = "Religion & Spirituality"
    sub_category = "Christianity"
    iTunes = "https://itunes.apple.com/us/podcast/tgc-word-of-the-week/id1034013280"
    feed = "https://www.thegospelcoalition.org/podcasts/word-of-the-week/feed/?feed=podcast"

  [params.contact]
    service = "custom"
    url = "https://api.wherwellcc.co.uk/sendmessage"
    #url = "http://localhost:7071/api/HttpTrigger1"

    [[params.links]]
      service = "Twitter"
      icon = "fa-twitter"
      icon_pack = "fab"
      colourhex = "#00acee"
      link = "https://twitter.com/wherwellcc"

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook facebook"
      icon_pack = "fab"
      colourhex = "#3f729b"
      link = "https://facebook.com/wherwellcc/"

    [[params.links]]
      service = "Instagram"
      icon = "fa-instagram instagram"
      icon_pack = "fab"
      colourhex = "#3f729b"
      link = "https://instagram.com/wherwellcc/"
